services:
  flask_app:
    build: .
    container_name: flask_api
    ports:
      - 80:80
    environment:
      - POSTGRES_IP=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: flask_db
    volumes:
      - ./rates.sql:/docker-entrypoint-initdb.d/rates.sql
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}